title: Open Coding 
description: "Class of 2026"
owner_name: Xavier Thompson
github_username: XavierTho
github_repo: "personal_student" 
baseurl: "/personal_student" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md